name: asunder

on: [push, pull_request]

jobs:
  test:
    name: Test - ${{ matrix.python-version }} - ${{matrix.os}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      uses: abatilo/actions-poetry@v2
      run: |
        poetry install
    - name: Test with pytest
      run: |
        make test